version: "3.7"

services:
  db:
    container_name: postgres-test
    image: postgres:13.2
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - PGPORT=5434
      - POSTGRES_DB=test-db
    volumes:
      - dbstore1:/var/lib/postgresql/data-test
    ports:
      - 5410:5434
volumes:
  dbstore1: